inhibit_all_warnings!

target 'YFQBaseProject' do
    use_frameworks!

    pod 'SDWebImage', '~> 3.7.5'
    pod 'SDWebImage/WebP'
    # 增加 transform 标记功能
#pod 'YYWebImage',
#pod 'YYImage/WebP'

    pod 'ReactiveCocoa', '~> 2.5'
    # 兼容 iOS11
    pod 'SwipeTableView'
    
    pod 'Masonry', '~> 1.1.0'
    pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
    pod 'FLAnimatedImage', '~> 1.0'
    pod 'IQKeyboardManager', '~> 4.0.8'
    # pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'SAMKeychain', '~> 1.5.2'
    pod 'YYCategories', '~> 1.0.4'
    pod 'YYText', '~> 1.0.7'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJRefresh', '~> 3.1.13'
    pod 'MJExtension', '~> 3.0.13'
    pod 'FMDB', '~> 2.6.2'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
#pod 'SocketRocket', '~> 0.5.1'
    pod 'MagicalRecord', '~> 2.3.2'
    # 检测内存泄漏 循环引用
    pod 'MLeaksFinder'
    pod 'YYCache','~> 1.0.4'
#pod 'PINRemoteImage/WebP'


end
